In [25]:
import numpy as np
total_figure = ([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
                 [0, 0, 1, 1, 1, 0, 1, 1, 1, 1],
                 [0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
                 [0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 1, 1, 1, 0, 0, 1, 0],
                 [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                 [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])
print(total_figure)
print(type(total_figure))
total_figure = np.array(total_figure)

find_one=[]
side = 10
count=0
island=0
size=0
print(total_figure)
##############找出所有矩陣中為元素為1的位置
for i in range(side):
    for j in range(side):
        if total_figure[i,j]==1:
            find_one.append([j,i])
print (find_one)####最後印出
################開始判斷

for c in find_one:
    buffer=[0]
    if total_figure[c[1],c[0]]==2:
        continue
    print("=====")
    island+=1
    size=0
    print("第",island,"座島")
        #將第一個不為零的矩陣位置改為checked並印出

    #初步尋找矩陣值不為零的座標
    if c[0]+1!=side: #邊界條件，整個圖片為10X10
        if total_figure[c[1],c[0]]==1: # x+1 位置判斷(往右一格)
            total_figure[c[1],c[0]]=3
            buffer.append([c[0]+1,c[1]])
            count+=1
    if c[0]-1!=-1:
        if total_figure[c[1],c[0]-1]==1: # x-1 位置判斷(往左一格)
            total_figure[c[1],c[0]-1]=3
            buffer.append([c[0]-1,c[1]])
            count+=1
    if c[1]+1!=side: #邊界條件，整個圖片為10X10
        if total_figure[c[1]+1,c[0]]==1: # y+1 位置判斷(往下一格)
            total_figure[c[1]+1,c[0]]=3
            buffer.append([c[0],c[1]+1])
            count+=1
    if c[1]-1!=-1:
        if total_figure[c[1]-1,c[0]]==1: # y-1 位置判斷(往上一格)
            total_figure[c[1]-1,c[0]]=3
            buffer.append([c[0],c[1]-1])
            count+=1
    
    #將第一個不為零的矩陣位置改為checked並印出
    total_figure[c[1],c[0]]=2
    print("初位置",[c[0],c[1]])
    
    
#     print(a) #目前狀況
#     print(buffer, count)
    
    #增加buffer格數並印出buffer
    for l in range(count,side+5):
        buffer.append([0,0])
#     print(buffer, count)

    #buffer功能
    while buffer[count]!=0:
        
        size+=1
        #目前判斷的位置
        print("目前位置: ",buffer[count])
        #偵測到1的數量
        add=0
        if buffer[count][0]+1!=10: #邊界條件，整個圖片為10X10
            if total_figure[buffer[count][1],buffer[count][0]+1]==1: # x+1 位置判斷(往右一格)
                total_figure[buffer[count][1],buffer[count][0]+1]=3 #將值命為pulled(3)
                add+=1
                buffer[count+add]=[buffer[count][0]+1,buffer[count][1]] #在buffer中新增元素為1的位置資訊
                print("---判斷---增加: ",[buffer[count][0]+1,buffer[count][1]])
        if buffer[count][0]-1!=-1:
            if total_figure[buffer[count][1],buffer[count][0]-1]==1: # x-1 位置判斷(往左一格)
                total_figure[buffer[count][1],buffer[count][0]-1]=3
                add+=1
                buffer[count+add]=[buffer[count][0]-1,buffer[count][1]]
                print("---判斷---增加: ",[buffer[count][0]-1,buffer[count][1]])
#                 print(buffer, count)
        if buffer[count][1]+1!=10:
            if total_figure[buffer[count][1]+1,buffer[count][0]]==1: # y+1 位置判斷(往下一格)
                total_figure[buffer[count][1]+1,buffer[count][0]]=3
                add+=1
                buffer[count+add]=[buffer[count][0],buffer[count][1]+1]
                print("---判斷---增加: ",[buffer[count][0],buffer[count][1]+1])
#                 print(buffer, count)
        if buffer[count][1]-1!=-1:
            if total_figure[buffer[count][1]-1,buffer[count][0]]==1: # y-1 位置判斷(往上一格)
                total_figure[buffer[count][1]-1,buffer[count][0]]=3
                add+=1
                buffer[count+add]=[buffer[count][0],buffer[count][1]-1]
                print("---判斷---增加: ",[buffer[count][0],buffer[count][1]-1])
#                 print(buffer, count)
            
        total_figure[buffer[count][1],buffer[count][0]]=2 #將目前的值令checked(2)
#  
        for k in range(count,count+add+1): #將buffer座標全部往前移
            buffer[k]=buffer[k+1]
        count=count+add-1 #接下來要測的座標
    
#         print(buffer, count)
        print(total_figure)
#         print("=====")

    if count==0:
        print("size=",size)
    
        
print("共",island,"座島")

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0, 0, 1, 1], [0, 0, 1, 1, 1, 0, 1, 1, 1, 1], [0, 0, 1, 1, 0, 0, 1, 1, 1, 1], [0, 1, 1, 1, 0, 0, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 1, 1, 1, 0, 0, 1, 0], [0, 0, 0, 1, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]
<class 'list'>
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 1 1]
 [0 0 1 1 1 0 1 1 1 1]
 [0 0 1 1 0 0 1 1 1 1]
 [0 1 1 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 1 1 0 0 1 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
[[1, 1], [2, 1], [3, 1], [4, 1], [8, 1], [9, 1], [2, 2], [3, 2], [4, 2], [6, 2], [7, 2], [8, 2], [9, 2], [2, 3], [3, 3], [6, 3], [7, 3], [8, 3], [9, 3], [1, 4], [2, 4], [3, 4], [6, 4], [7, 4], [8, 4], [8, 5], [3, 6], [4, 6], [5, 6], [8, 6], [3, 7], [4, 7], [5, 7], [6, 7], [3, 8], [4, 8], [5, 8], [6, 8], [6, 9]]
=====
第 1 座島
初位置 [1, 1]
目前位置:  [2, 1]
---判斷---增加:  [3, 1]
---判斷---增加:  [2, 2]
[[0 0 0 0 0 0 0 0 0 0]
 [0 2 2 3 1 0 0 0 1